# Generated by Django 2.0.2 on 2018-02-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comander', '0002_worker_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'data'},
        ),
        migrations.AlterField(
            model_name='worker',
            name='input_params',
            field=models.CharField(max_length=100),
        ),
    ]
