# Generated by Django 2.0.2 on 2018-02-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comander', '0003_auto_20180227_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='run_command',
            field=models.CharField(max_length=100),
        ),
    ]
