# Generated by Django 2.0.2 on 2018-02-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comander', '0004_auto_20180227_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
